### ISSUE TITLE
connexion problem with rolisteam

### ISSUE THREAD

**Issue by RussianNinjaCop** [Rolisteam/rolisteam#2]
Hi, I Apologize in advance for my bad english, it is not my native language.

I'm creating this messages to try to find a solution about a problem in rolisteam :

We are 4 players and one Game master and a problem happens to one player only :

He is disconnected from the lobby randomly (sometimes he is here 20 minutes, then he is disconnected every 1 or 2 minutes) while the others players don't have any problem.

Do you know a way to fix that ? 

Best Regards.

**Comment by obiwankennedy** [comment]
Hi, 

This kind of behaviour is often due to anti-virus software, anti-malwares or any security software (firewall). Some anti-virus have firewall feature as well.
Some of them have action on network and can cut the connection.

I recommend to disable (or shut down ) it for the time of the game. It may have parameters to fix the problem. 
Do you have any informations on the computer which has issue ? system, version of rolisteam, security software ? 

I hope that help! 
Best regards
___________________
En français,
J'ai souvent vu ce comportement avec des postes ayant un anti-virus/anti-malwares/ parefeu assez violent.
C'est lui qui coupe la connexion après quelques temps. Il faudrait vérifier s'il n'y a pas de service qui tourne sur sa machine ou sur son routeur/box… pour soit le désactiver, soit le configurer pour qu'il arrete. 

Avez-vous des détails sur la machine en question ? Son système, la version de rolisteam, des logiciels de sécurité, le moyen d'avoir internet ?

J'espère que cela aide.
Cordialement.
